on: [push]

name: CI

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    name: Rust project
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions/upload-artifact@v2
        with:
          name: Artifact
          path: target/release