name: Rust Mac

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose --no-default-features --features metal
      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v1
        with:
          name: Mac Build
          path: target/debug