name: Rust Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose --no-default-features --features vulkan

      - name: Cache Leftovers
        uses: actions/cache@v2
        with:
          path: ~/target/debug
          key: rust-windows

      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v1
        with:
          name: Windows Build
          path: target/debug